### PR TITLE
[TD] fix SVG metadata

### PR DESCRIPTION
**Pull request by luzpaz**
Rename missed filenames in SVG metadata

### CODE REVIEW

**Comment by luzpaz** [comment]
@bitacovir do a merge with 'fast-forward' enabled

**Comment by bitacovir** [comment]
@luzpaz I already edited the files in https://github.com/FreeCAD/FreeCAD/pull/4779/files

**Comment by luzpaz** [comment]
you missed an edit. See  0143b52

**Comment by bitacovir** [comment]
@luzpaz Ok. I have fixed it. Thanks.

**Pull request closed without merging**
